{% set name = "xaitk-jatic" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/xaitk_jatic-{{ version }}.tar.gz
  sha256: dd8be4995b3221d54ce23c683780257695555fd8a9e532ce2315eb1fd8cbd920

build:
  skip: true  # [win]
  entry_points:
    - sal-on-coco-dets = xaitk_jatic.utils.bin.sal_on_coco_dets:sal_on_coco_dets
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - pip
    - poetry-core
  run:
    - python
    - xaitk-saliency >=0.9.2
    - maite >=0.6.0
    - setuptools >=65.6.3
    - scipy >=1.10
    - numpy >=1.22,<2.0
  run_constrained:
    - kwcoco >=0.2.18
    - matplotlib >=3.4.1
    - transformers ~=4.42.3
    - timm ~=1.0.7
    - torchvision >=0.10.0

test:
  imports:
    - xaitk_jatic
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/xaitk-jatic/
  summary: |
    "Bucket" to house various examples and resources related to
    xaitk-saliency (https://github.com/XAITK/xaitk-saliency) integration
    and scaling for JATIC use as part of the JATIC program.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bjrichardwebster
    - barry-ravichandran
    - eveenhuis
